### ISSUE TITLE
[Feature Req.] Option to save coeval T21 boxes at all intermediate z, instead of just the endpoint

### ISSUE THREAD

**Issue by JulianBMunoz** [21cmfast/21cmFAST#164]
Right now each coeval box has a structure associated with it, including initial condition (IC) boxes, etc. So if a user needs the 21cm coeval box at many z there will be many unnecessary copies of the ICs, taking a lot of disk space.

Ideally, we could add an option to save all intermediate coeval boxes between Z_HEAT_MAX and the z indicated by the user. Since those are calculated anyway it's just a matter of saving to disk if requested (maybe warning the user it'd take more space than standard).

Another possibility, mentioned by @steven-murray , is to save all coeval boxes independently, but linking to the same IC cached file. It might be a problem if the IC file gets deleted.

**Comment by steven-murray** [comment]
There are  a few things to think about here. Firstly, right now, the actual `Coeval` box is created right at the end of `run_coeval`, by passing in relevant boxes that it requires. It's really just a class that contains stuff, nothing too special going on (although it does have the `save/read` methods). If we were to save multiple redshifts defining the full history, we'd have to keep track o them all in `run_coeval`, which we don't currently do (we only keep two in memory at a time, for obvious memory reasons). Furthermore, the Coeval really would be more of a lightcone with all that info! That could be OK, and perhaps we even want to do this explicitly for the Lightcone object (i.e. save full 3D boxes at each redshift, and have a method to stitch them together). But we should think carefully about the API.

The other thing is, if caching is switched on (and it is by default), then all of those intermediate boxes are _already_ being written into the cache. It seems redundant and inefficient to then also save that data into the Coeval box. HDF5 files support symlinks, I'm pretty sure, so we could always try to use those to link to the actual cached data. But then you have the problem that if the cached data is removed for some reason, then the Coeval file is essentially corrupted. In fact, the idea of the Coeval file was supposed to be a file that's easy to share. You couldn't share it easily if it depends on other files. 

We could potentially write a method on the Coeval class that is able to "pack up" the file and insert all the symlinked data explicitly, to be shared. But I can see this leading to lots of things breaking (what if you already deleted the symlinked data?) The data that is symlinked probably cannot know about the Coeval file, so we can't even raise any warnings/errors when deleting it. Obviously, we have no way of doing this if the user deletes it manually from the filesystem.

One potential way around this is to manage it all for the user within some kind of explicit database. That is, maintain an explicit database of current cached data, and include Coeval boxes as cached data. Then everything can be cross-linked and proper warnings can be issued if child data is going to be removed. But this is a lot of extra complexity, and I'm not sure we want to go down that road. I'll let @BradGreig and @andreimesinger comment on that. 

Another way around this is to make things _more_ simple than they already are and go back to something more akin to what the original 21cmFAST did -- have an output directory for any particular calculation, and let all products of the simulation be output there (they need to be output somewhere for memory reasons). The products get written into a unique _subdirectory_ there corresponding to the input parameters used (or a user-chosen label). That directory is assumed to be complete, and Coeval boxes are written into that directory as well. It is assumed that the user will take care of not deleting stuff in that directory that they need. 
The problems with this approach are 1) it's not really _that_ much more simple than what we have, 2) it's not a very interactive-friendly method (i.e. how do we decide on what one "calculation" is to save in a unique directory? -- one function call? one user session?) and 3) it's not quite as efficient overall, since in reality, a new session using the same parameters can benefit from the cache. 

In fact, we kind of already have this ability -- the user gets to set the output directory, and each cache file will be output there. We could just try trusting the user to use that functionality and not delete files in there if they intend on sharing. Might be asking too much of the user....

So, in the end, I'm really just not sure what the best way is.

**Comment by steven-murray** [comment]
Let me outline a potential solution:

We modify `run_coeval` so that  the cache filenames of all intermediate boxes will be gathered throughout the evolution (we'll have to ensure that `write=True` I guess). Then add an extra keyword to `Coeval` into which these filenames can be passed. Then  define a new method on `Coeval` like `gather()` which will get all the contents of those cached files, and pull them into the actual `Coeval` file so they're all consistent and in one place. We could also give `gather` a keyword like `clean=False`, which if `True`, would delete the original cache files (potentially, it could be a dict that specifies which kinds of cache files to delete -- sometimes you might want to not keep the many spin temp boxes, but want to keep the ICs for example). One point to mention -- the `gather` should be gathering the extra files _into the savefile_ (i.e. not into memory).

Then the `run_coeval` will just output a standard `Coeval` box, but it would have the links to the extra files which could be read and gathered if desired by the user explicitly.

Thus, by default, there are _links_ to extra files in the `Coeval` class, which don't take more memory or disk space. This is a bit brittle, because those files may be deleted and the file would then not have access to them. But it is unavoidable. And then we'd be providing the user an easy way to avoid the brittle-ness at the expense of disk space if they so desired.

**Comment by steven-murray** [comment]
@JulianBMunoz another workaround to this is to use the `direc` option to save everything that's produced in cache to that specific directory, in which case you can find it all easily.

**Comment by steven-murray** [comment]
Apologies, @JulianBMunoz, my previous suggestion only fixes some of the problem -- it would mean all intermediate boxes are saved to cache (in a particular directory where they could be packaged up), but it would still take a lot more space then really required. 

The [solution I outlined above that](https://github.com/21cmfast/21cmFAST/issues/164#issuecomment-669193964) would solve this problem, but is admittedly quite involved (and we've starting implementing it). However, I think another route here is to adapt the new callback feature for `run_lightcone` to `run_coeval`. This would be able to do _whatever you want_ for each coeval box. You could manually write a function that would save everything optimally to a single file, if you want to.
