### ISSUE TITLE
update the default parameters for UserParams and FlagOptions

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#186]
**Is your feature request related to a problem? Please describe.**

This issue aims to update the default parameters. Please post any other required updates below.

**Describe the solution you'd like**

I think we have decided to set `PERTURB_ON_HIGH_RES=1` by default. 

Also, I strongly suggest to automatically set `USE_INTERPOLATION_TABLES=1` when `USE_MASS_DEPENDENT_ZETA==1`. I've been trapped by this many times. We can return a warning saying that 
```
You have set USE_MASS_DEPENDENT_ZETA to True but USE_INTERPOLATION_TABLES to False! "
                "Automatically setting USE_INTERPOLATION_TABLES to True."
```
If we really want to support running with `USE_MASS_DEPENDENT_ZETA=1` and `USE_INTERPOLATION_TABLES=0`, we can probably just give a warning without changing `USE_INTERPOLATION_TABLES`... What do people think?

**Describe alternatives you've considered**

**Additional context**

**Comment by andreimesinger** [comment]
i would provide 2 sets of parameter files, allowing the user to select between "fastest" and "more accurate".  current defaults seem to be the "fastest" variety

**Comment by steven-murray** [comment]
This is highly related to #85, and set for implementation reasonably soon. Note however that updating defaults is only allowed on a MAJOR version increase. I'm all for adding a warning in the interim, and then providing "sets" of defaults as per #85 in v3.2.0.

**Comment by BradGreig** [comment]
I agree a warning can be thrown up, however, I disagree with automatically changing it under certain conditions. Once the defaults are changed, you shouldn't run into the problem of incorrectly turning having it on/off.

**Comment by qyx268** [comment]
okay then, I will make a PR only warn the user when USE_MASS_DEPENDENT_ZETA=1 and USE_INTERPOLATION_TABLES=0

**Comment by steven-murray** [comment]
I agree with @BradGreig

**Comment by andreimesinger** [comment]
why is updating defaults only for major release?  it doesn't break APIs...  should i go through the files and suggest settings for "fast" and "more accurate" combinations?

**Comment by steven-murray** [comment]
@andreimesinger  I think it's debatable if it breaks the API. It certainly won't break anyone's code. However, it may change results of some code that doesn't set all parameters explicitly. I'd say this is "breaking". You could convince me otherwise though :-)

And yes! That would be very helpful. @BradGreig and I also discussed having other sets of defaults that correspond to "famous" runs (eg. those from the EoS or other papers). 

With the new "sets" of defaults, we can leave the current default defaults in place, and just add documentation about how to switch to the other sets. This can be done prior to a major version (and we can update the default defaults at v4).

**Comment by qyx268** [comment]
@steven-murray I'm about to add a warning for this but it looks like having `USE_MASS_DEPENDENT_ZETA` in `FlagOptions` and `USE_INTERPOLATION_TABLES` in `UserParams` makes it not straightforward. I'm wondering why we didn't put `USE_INTERPOLATION_TABLES` (and perhaps also `USE_FFTW_WISDOM` and `USE_RELATIVE_VELOCITIES`) in `FlagOptions` in the first place? In fact, with the current structure, it looks like there is no such a necessity of having `UserParams` and `FlagOptions` separated.

**Comment by steven-murray** [comment]
@qyx268 -- `FlagOptions` is not passed to `initial_conditions`, which is why those two have to be in `UserParams`. You're right that this makes it a little tricky to do validation on combinations of parameters from different structs. 

I have been thinking about how to do this more generally, and I'm not sure what the best option is... perhaps it's to create one "validation" function that gets called every time a function has input structs? It would optionally take a struct of every kind, and then do comparisons on parameters and issue warnings/errors depending on their combination. I'd _prefer_ the validation to be done _in_ the object itself, but then it needs to know about the other parameters. You could make a function `validate_inputs` that goes in `inputs.py`, with signature like:

```python
def validate_inputs(*, user_params=None, cosmo_params=None, flag_options=None, astro_params=None):
   if user_params and user_params.USE_INTERPOLATION_TABLES and flag_options and flag_options.USE_MASS_DEPENDENT_ZETA:
       warnings.warn("warning...")

   <other conditions...>
```

**Comment by qyx268** [comment]
It's very similar to `_verify_types`, which raise errors instead of warnings. However, if we do this to simply warn the user, aren't they going to get the same warnings for multiple times as we will call `_validate_inputs` every time when a function having inputs (which is basically every function that is not only used internally) is called?

**Comment by steven-murray** [comment]
@qyx268 Python limits warnings with the same message to be output once per
session, so this shouldn't be a problem. Yes, very similar to the
`_verify_types`.

**Comment by qyx268** [comment]
well, I ended up following what we are doing with using `INHOMO_RECO` from `FlagOptions` in `AstroParams` rather including `_validate_inputs`.

**Comment by qyx268** [comment]
hmm... what's the reason of having `USE_INTERPOLATION_TABLES` in `UserParams` then? Can't we just put it in `FlagOptions`? I dont think we are using `USE_INTERPOLATION_TABLES` for the initial condition, are we? Unless I'm missing soemthing, I dont think we are using `HMF` or `POWER_SPECTRUM` either to generate the initial condition.

**Comment by steven-murray** [comment]
`POWER_SPECTRUM` is definitely used by initial conditions. HMF might be
used by perturb? If `USE_INTERPOLATION_TABLES` is only used in spin
temperature or later, then it should be in `FlagOptions`. If so, we should
deprecate it in `UserParams`. I was thinking that doing the same as
`INHOMO_RECO` is not very scalable, as we need to change the constructor
everywhere we create the object. Maybe I'm not remembering correctly though?

**Comment by BradGreig** [comment]
As @steven-murray pointed out, `POWER_SPECTRUM` is used to generate the ICs and `HMF` can be used by `PerturbField` and `FindHaloes`. `USE_INTERPOLATION_TABLES` decides whether to compute `sigma(M)` explicitly or using an interpolation table, which makes things faster/slower. Though, only noticeable when `USE_MASS_DEPENDENT_ZETA` is `False`.
