### ISSUE TITLE
Installing on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by kmbasad** [21cmfast/21cmFAST#190]
I faced some difficulties in getting to run 21cmFAST on Ubuntu 18.04 LTS, but it is running smoothly now. I just wanted to keep the steps I took noted here for future reference and possibly also for others.

After installing anaconda3 on Ubuntu 18.04 LTS, create a new conda environment: `conda create -n myenv python=3.6`

Activate the environment: `conda activate myenv`

Install gsl and fftw: `conda install -c conda-forge gsl fftw`

Other dependencies are automatically installed while installing 21cmFAST using conda-forge as (do not forget to specify the LIB and INC paths before the conda command)

```
LIB=~/anaconda3/envs/myenv/lib INC=~/anaconda3/envs/myenv/include conda install -c conda-forge 21cmFAST
```

21cmFAST is now installed, but I could not run the example scripts because I did not have a "user data" directory in my home. So download or clone the 21cmFAST github package `https://github.com/21cmfast/21cmFAST`, unzip and then move only the `user_data` directory to your home folder. Finally rename this directory to `.21cmfast` (a hidden directory):

```
mv ~/Downloads/21cmFAST/user_data ~/
cd
mv user_data .21cmfast
```

Then the following code should run smoothly:

```
import py21cmfast as p21c
coeval8, coeval9, coeval10 = p21c.run_coeval(
    redshift = [8.0, 9.0, 10.0],
    user_params = {"HII_DIM": 100, "BOX_LEN": 100, "USE_INTERPOLATION_TABLES": True},
    cosmo_params = p21c.CosmoParams(SIGMA_8=0.8),
    astro_params = p21c.AstroParams({"HII_EFF_FACTOR":20.0}),
    random_seed=12345
)
```

**Comment by steven-murray** [comment]
@kmbasad thanks so much for the detailed report! Hopefully this will help some users. 

The fact that the `user_data/` directory isn't copied when doing a `conda` install is definitely a bug. I will try to fix that soon.

With `conda` you shouldn't have to explicitly install `gsl` and `fftw` -- they should be installed in the one command, simply `conda install -c conda-forge 21cmFAST`. If that is not working properly, it is also a bug in the `conda-forge` feedstock.

**Comment by Andresfgomez970** [comment]
Good day, 

First of all, thank you very much for your hard work and sharing this library with the world. I am trying to learn a little right now but I am having the same problem mentioned in this  issued.  However, I am not actually finding the user_data directory on the repo. Any idea of how to solve it would be greatly appreciate it.

**Comment by steven-murray** [comment]
Hi @Andresfgomez970, 

First, thank you for using 21cmFAST! Secondly, the most recent versions of 21cmFAST should automatically install the user-data to the correct place, so I'm not sure why you are having those issues. The user-data directory now exists inside the package itself, instead of at the top-level, so it can be found automatically by the package.

1. Yes, running 21cmFAST can take a bit of RAM. You might want to set the `HII_DIM` lower. You can also follow this PR (#221 ) which is aiming to add an easy way to estimate the memory usage of a particular run.
2. You can set `NTHREADS=4` in `user_params` to get shared-memory parallelization. We don't recommend using more than about 4 threads because it does not scale very well past that unfortunately. Perhaps @qyx268 can comment further here.

**Comment by steven-murray** [comment]
Hi @Andresfgomez970, if you had trouble with doing a local pip install, can you make an issue about it with some detailed outputs? I for instance have no problem with a local pip install.

IN terms of parallelization, the problem is largely due to the type of problem, and the fact that we need sequential evolution of the universe (and also, there's a memory issue that plays into it).

**Comment by Andresfgomez970** [comment]
Thanks again for the quick answer. I will probably be opening an issue in the future related to the pip installation then.

**Comment by qyx268** [comment]
Indeed, we tested the scaling with normal-sized runs (e.g. HII_DIM=250 in the JOSS paper) and found >4 cores did not help too much. However, for bigger runs, I believe having more cores will still help.
