### ISSUE TITLE
[BUG] FFTW wisdom files have scrambled names

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#209]
**Describe the bug:**

FFTW wisdoms are being saved into the correct directory, but ALSO into the current working directory, with the wrong name.

**To Reproduce:**
1. `21cmFAST coeval 7.0`

**Expected behavior:**

We shouldn't get a copy in the current directory at all.

**Details:**
 - OS: [e.g. iOS] MacOS (maybe others)

**Comment by BradGreig** [comment]
Hey @steven-murray, I notice that the master branch now contains a couple of examples of these wisdom files I was mentioning. For [example](https://github.com/21cmfast/21cmFAST/blob/master/c2r_DIM-856800688_NTHREADS25).

**Comment by qyx268** [comment]
ah, this is just because that we missed %s here:
https://github.com/21cmfast/21cmFAST/blob/2b11302e3f44527c8947d58494a677317cecc8f4/src/py21cmfast/src/dft.c#L97
and 
https://github.com/21cmfast/21cmFAST/blob/2b11302e3f44527c8947d58494a677317cecc8f4/src/py21cmfast/src/dft.c#L105

I fixed it in #210 although I also noticed that we need to manually mkdir ~/.21cmfast/wisdoms before running 
`python -c "import py21cmfast as p21c; p21c.construct_fftw_wisdoms(user_params={'USE_FFTW_WISDOM': True, 'HII_DIM':25})"  `

**Comment by steven-murray** [comment]
Yup, @qyx268  is right about missing the %s. 

You should not need to manually do `mkdir`. Whenever the `global_params` is constructed, it automatically creates the folder if it doesn't exist (see lines 310-311 of `inputs.py`).

**Comment by qyx268** [comment]
fixed by #210
