### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by PaulineGorbatchev** [21cmfast/21cmFAST#354]
Hello, thank you for sharing this repository. 

I encountered 2 issue when running the mini-halos jupyter notebook tutorial:

1) Warning
Your configuration file is out of date. Updating...
  warnings.warn("Your configuration file is out of date. Updating...")

2) Error
ModuleNotFoundError: No module named 'py21cmfast.c_21cmfast'

**Details:**

 - OS: MacOS Monterey
 - Python Version: 3.11.7
 

**Additional context**

For issue 1) I saw that #242 had a similar problem on Ubuntu, and I saw that he was redirected to #190 where it was said that the directory /user_data needs to be copied manually, but I cannot find it on the GitHub repository. Can this warning be ignored or will it impact something?

For the issue 2), can you please explain to me what exactly is py21cmfast, because in the __init__.py file it is called a package but the error called it a module, and what I need to do in order to correct the error? (I have tried re-installing with conda, with pip and also downloading the code manually from the GitHub page)

Thank you very much

**Comment by steven-murray** [comment]
Hi @PaulineGorbatchev -- sorry for not seeing this earlier!

OK, for (1), this is not a problem. The warning should not be being raised (this will be fixed in an upcoming release). So just ignore the warning.

For (2) -- this indicates that the compiled C library is not being found. Are you sure you are using the correct python installation? That is, if you have installed py21cmfast into a python environment (eg. with conda), then make sure the Python you are using is from the correct environment.

**Comment by steven-murray** [comment]
@PaulineGorbatchev please feel free to re-open if you are still having trouble. Otherwise I am closing this as stale.
