### ISSUE TITLE
method for accessing coeval data different and not documented correctly [BUG]

### ISSUE THREAD

**Issue by catherinewatkinson** [21cmfast/21cmFAST#52]
Not so much a bug as something I think needs rethinking/revising.

I am just trying to run using run_coeval using some existing code with the most up-to-date 21cmFAST and I am having to work out how to access the boxes all over again by trawling through the code itself. The new method using a Coeval class containing a load of other classes is returning an Class object containing classes of classes for each coeval type. Unlike before where it returned the individual coeval classes, each containing a list of the coeval at each redshift were returned. 

I have a couple of issues with this:
1. Could we perhaps decide on the higher level interfacing ASAP and stop changing it until the next major release (and even then only if absolutely essential). It is incredibly irritating to have to waste time debugging established code. This made worse by the fact the documentation doesn't appear to be keeping up with these high-level tweaks . I also had something similar with the power spectrum noisefile changing what string it used to access the dictionary contents. Which I adjusted code to allow for and now it has changed back to the old method so I have to do this all over. #wingeover ;)

2. It seems quite convoluted to have to use nested classes to get to the coeval data. i.e. 
coevals = p21.run_coeval( redshift = redshifts, user_params = UParams, astro_params=AParams, flag_options=FOptions, write=False)

box = coevals[0].brightness_temperature.brightness_temp

I've just also realised, 21cmMC is not compatible with the new coeval class method.

**Comment by steven-murray** [comment]
Thanks @catherinewatkinson. I admit that the `Coeval` class addition was my fault. I do happen to think it's better than what was before, but you are quite right to highlight the irritating nature of backwards-incompatible API changes. 

Going forward, the versioning scheme should make this issue disappear -- API-breaking changes are _only_ allowed for major version changes (i.e 2.x.x --> 3.0.0). However, we are working towards our 3.0.0 currently (we're on 3.0.0alpha), and so we need to decide on the high-level API before we switch to 3.0.0. Until then, unfortunately, the API will not be set in stone (we need it to be relatively fluid now, otherwise we won't be able to get it as right as we want for that first proper release).

In that vein, what do you suggest for the API here? What is the most obvious output for you? For me, the downside of the previous output was that if we wanted to pass some other data back from `run_coeval`, it would instantly break the API again. Now, if whatever we pass back is part of the `Coeval` object, it doesn't break anything to break the internals of that object. 

The `21cmMC` calls are fixed in the current `memory-leak` branch over there, which should be merged very soon.

**Comment by catherinewatkinson** [comment]
I agree that passing back a single class, such as Coeval is neater. However, it would be far cleaner to do so without it containing nested classes, so you can access the data with e.g. Coeval.brightness_temp

**Comment by steven-murray** [comment]
I agree that would be nice. Perhaps we could do something like

```python
class Coeval:
    def __init__(self, init, perturb, ionize, spin_temp, brightness_temp):
        # Keep the original classes so that we have name-spaced access to their attributes
        self._init = init
        self._perturb = perturb
        self._ionize = ionize
        self._spin_temp = spin_temp
        self._brightness_temp = brightness_temp

        self.user_params = brightness_temp.user_params
        ... # etc. for all the parameter dicts

        # Make all C-level fields (especially arrays) visible directly in the Coeval class
        for field in init.fields:
            setattr(field, getattr(init, field))

        ... # and so on for all classes

        # Also probably want to do some validation that the user params etc. are the same between each class.
```

What do you think @catherinewatkinson ? @BradGreig ?

**Comment by catherinewatkinson** [comment]
So if I understand right. You would access the boxes with Coeval._brightness_temperature? Not loving the additional _, seems pointless when you could call the passed arguments something different. Otherwise, it seems sensible.

**Comment by steven-murray** [comment]
The prefixed underscore makes them "semi-hidden" in python -- i.e. they're understood to be private (though they're still fully accessible, they don't show up when for instance you press `<tab>` on the class in the interpreter, so they don't clutter up the namespace). My idea was that they shouldn't normally need to be accessed in the normal course of things, since their useful properties have been exposed directly on the `Coeval` class, but for the experienced user, they can still get to them. The other concern is that it will get confusing with names like `brightness_temp` (the class) and `brightness_temp` (the array). 

Do you have a reasonable suggestion for different things to name them if we wanted to keep them all public?
