### ISSUE TITLE
Minimise memory usage for InitialConditions class

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#63]
**Describe the bug:**
The InitialConditions class initialises all possible memory even if certain options are turned off (e.g. it declares memory for 2LPT and relative velocities even if these options are turned off). 

**Additional context**
The InitialConditions class is the heaviest memory user, thus it would be preferred if this can be minimised if possible by including flags in the class to only initialise memory that is required.

**Comment by steven-murray** [comment]
I think this issue can be augmented in that when reading the cached initial conditions, not all components of the initial conditions are always needed -- sometimes we might just need one or two boxes in the structure. 

I think this can be solved by lazy-loading from the HDF5 files. 

Of course, a true full load is required before handing it off to C.

**Comment by BradGreig** [comment]
Yeah, I was thinking of something similar. That when reading from cache, we are able to pre-define the relevant pieces of information to look for and load into memory. I think this structure will be necessary for quite a few classes.

**Comment by JulianBMunoz** [comment]
As a small note, the relative velocity boxes, which are part of the initial conditions, are used within Ts and Ionizations. So it'd indeed be useful to not get rid of all the InitialConditions, or perhaps save and read the ones we care about.

**Comment by JulianBMunoz** [comment]
Also, related to #69 , it seems to me that big-box runs are pretty unfeasible right now, given the memory requirements. It'd be good to think of a possible workaround/solution to run big boxes without big (memory) bucks.

**Comment by qyx268** [comment]
@JulianBMunoz My impression is that it would take a while to properly implement functions that allow us to read part of the IC. If you wanted to do some big run at the moment, you could take a look at my `skip_init` branch (do git diff HEAD~1 to see the changes, I haven't updated this branch with master for a while). It is a quick hack that skip reading the init and allows us to not store IC in the RAM when running an MCMC

**Comment by steven-murray** [comment]
In about two weeks I should have time to start working on the "proper" solution to this.

**Comment by JulianBMunoz** [comment]
@qyx268 that's a good tip, thanks! For the relvels we only need the lowres box, so perhaps a good solution for now might be to create a new RelVel class that saves that box at the end of initialconditions. We could re-evaluate what to do when we have a solution

**Comment by steven-murray** [comment]
Hey @JulianBMunoz, #220 does have the functionality you requested -- essentially it allows a two-stage "purging" of ICs memory, which is used within `run_coeval/run_lightcone`. It purges some of its memory right after it's calculated (since some of the boxes aren't used at all in further calculations), then again after `perturb_field` has been called. The functions that are called to purge the memory take the `flag_options` as a parameter (and also have access to `user_params`), so they can make intelligent decisions about what to dump. They also only dump if the ICs have been cached to file (otherwise the data would be irretrievably lost). However, this last restriction can be forcibly overridden if you just don't care about having the ICs afterwards.

 Check it out!

**Comment by JulianBMunoz** [comment]
Very cool @steven-murray, great work (and thanks for the heads up)! I have only taken a quick glance at #220, but it seems to do what we want. I like the granularity solution.

Is it right that if you’re perturbing in hi-res it only purges the low-res IC boxes? So if I’m running a box down to some z (with Ts so it needs to track the history) It will purge the low-res boxes after the ICs, and then keep the hi-res ICs to do perturb at each z? 

Also, why is the rel-vel box required in outputs.py in the in prepare_for_perturb and also in prepare_for_spin_temp?

**Comment by steven-murray** [comment]
Hi @JulianBMunoz, thanks for taking a look through! As I said in the PR itself, there's almost certainly more we can do to optimize things, especially with the new structure I've built around it -- so having more eyes on it is good!

You're right that it only purges the low-res if you're using `PERTURB_ON_HIGH_RES` (that is, before the `perturb_field`). However, I also modified the `run_coeval` and `run_lightcone` functions so that _all_ the perturb calls are done in their own loop before the Ts/ionize are run, so then we purge essentially the whole ICs. Slightly problematically, this is a little _less_ optimal in terms of the memory from the `PerturbField` objects (i.e., you either need all of them in memory at once, or you need to write to disk and read back in). However, I'd say that typically the memory reqs for _all_ perturb field boxes is similar to a single ICs (~27 redshifts would make it equal, I think). 

I found that the `lowres_vcb` was being used in obtaining the spin temperature, so could not purge it. If using relvels, that is the only box from the ICs that remains through the whole computation.

**Comment by JulianBMunoz** [comment]
Aha, that makes sense! The whole writing to disk + reading may be a good option for people who are more strapped for RAM than for disk space/time. It's a tradeoff. That was the case of the old 21cmFASTv2, and it helped me run big boxes in my laptop.

Also that's good about the `lowres_vcb`, thanks! I re-wrote it to only be on low-res, so that's not a lot of memory.

Thanks Steven!
